### ISSUE TITLE
Add `prettier` and config for client

### ISSUE THREAD

**Issue by johndturn** [ngoue/isthismoviegoodorbad#2]
This will standardize our coding style to avoid arguments and git diffs down the road. 

Please post opinions on prettier config settings (https://prettier.io/docs/en/options.html)

**Comment by johndturn** [comment]
```javascript
{
  printWidth: 120,
  singleQuote: true,
  trailingComma: 'all',
  arrowParens: 'always',
}
```

**Comment by tgroshon** [comment]
`printWidth: 90`
